language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - composer self-update
  - composer update --prefer-lowest

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
